function displayCndInfo(S, data)
    list_fields = fields(data);
    % take out the nonius lines structure and display info
    
    excludedFields = ismember(list_fields, 'nonius') + ...
        ismember(list_fields, 'handle') + ...
        ismember(list_fields, 'name');
    
     list_fields = list_fields(~excludedFields) ;

    
    for f = 1:numel(list_fields)
        % text
       uicontrol('style','text',...
                 'unit','normalized',...
                 'position',[0.05 0.35 - 0.03*f 0.15 0.15],...
                 'backgroundc',get(S.fh,'color'),...
                 'fontsize', 12, 'HorizontalAlignment','left', ...
                 'string', list_fields{f}, 'visible', 'on');
        
        %data
        val = data.(list_fields{f});
        if(isnumeric(val))
            dataStr = num2str(val);
        else
            dataStr = val;
        end
        uicontrol('style','text',...
                 'unit','normalized',...
                 'position',[0.17 0.35 - 0.03*f 0.15 0.15],...
                 'backgroundc',get(S.fh,'color'),...
                 'fontsize', 12, 'HorizontalAlignment','left', ...
                 'string', dataStr, 'visible', 'on');
             
    end    
end
