function gui = guiLayout(strName, conditionsList, conditionPos)

    gui.fh = figure('units','normalized',...
              'position',[0 0 0.8 0.8],...
              'menubar','none',...
              'name','SceneEditor',...
              'numbertitle','off',...
              'resize','on');
   
    uicontrol('style','text',...
                 'unit','normalized',...
                 'position',[0.05 0.8 0.25 0.2],...
                 'backgroundc',get(gui.fh,'color'),...
                 'fontsize', 16, 'fontweight','bold',... 
                 'string', strName, 'visible', 'on');

    %% conditions
    uicontrol('style','text',...
                 'unit','normalized',...
                 'position',[0.05 0.55 0.15 0.15],...
                 'backgroundc',get(gui.fh,'color'),...
                 'fontsize', 16, 'fontweight','bold',... 
                 'string', 'Conditions','visible', 'on');

    gui.popCnd = uicontrol('style','pop',...
                 'unit','normalized',...
                 'position',[0.05 0.52 0.15 0.15],...
                 'backgroundc',get(gui.fh,'color'),...
                 'fontsize',12,'fontweight','bold',... 
                 'string',conditionsList, 'value', conditionPos);
            
    gui.pbPlot = uicontrol('style','push',...
                 'units','normalized',...
                 'position',[0.05 0.5 0.15 0.05],...
                 'backgroundcolor','w',...
                 'HorizontalAlign','center',...
                 'string','Plot condition',...
                 'fontsize',14,'fontweight','bold');
             
             
    gui.chkBox = uicontrol('style','checkbox',...
                 'units','normalized',...
                 'position',[0.2 0.5 0.15 0.05],...
                 'backgroundcolor','w',...
                 'HorizontalAlign','center',...
                 'string','Stimset Trajectory',...
                 'fontsize',14,'fontweight','bold');
             
    %% axes position
     % plot left eye trajectories
     gui.pos_left = axes('units','normalized', ...
            'position',[0.35 0.03 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');

     % plot right eye trajectories
     gui.pos_right = axes('units','normalized', ...
            'position',[0.35 0.27 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');
        
     %plot vergence/version             
     gui.pos_verg = axes('units','normalized', ...
            'position',[0.35 0.53 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');
        
     gui.pos_vers = axes('units','normalized', ...
            'position',[0.35 0.78 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');
       
        
     %% axes velocity   
     gui.vel_left = axes('units','normalized', ...
            'position',[0.68 0.03 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');

     % plot right eye trajectories
     gui.vel_right = axes('units','normalized', ...
            'position',[0.68 0.27 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');
        
     %plot vergence/version             
     gui.vel_verg = axes('units','normalized', ...
            'position',[0.68 0.53 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');
     
     gui.vel_vers = axes('units','normalized', ...
            'position',[0.68 0.78 0.25 0.21], ...
            'xtick',[],'ytick',[], 'box', 'on');

        
    fontSettings = {'fontsize', 14, 'fontweight','bold'};
    set(get(gui.pos_left, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.pos_left, 'YLabel'), 'String', 'Position Left Eye(deg)', fontSettings{:});
    
    set(get(gui.pos_right, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.pos_right, 'YLabel'), 'String', 'Position Right Eye(deg)', fontSettings{:})    
    
    set(get(gui.pos_verg, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.pos_verg, 'YLabel'), 'String', 'Pos Vergence(deg)', fontSettings{:})    

    set(get(gui.pos_vers, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.pos_vers, 'YLabel'), 'String', 'Pos Version(deg)', fontSettings{:})    

    set(get(gui.vel_left, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.vel_left, 'YLabel'), 'String', 'Velocity Left Eye(deg/s)', fontSettings{:});
    
    set(get(gui.vel_right, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.vel_right, 'YLabel'), 'String', 'Velocity Right Eye(deg/s)', fontSettings{:})    
    
    set(get(gui.vel_verg, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.vel_verg, 'YLabel'), 'String', 'Velocity Vergence(deg/s)', fontSettings{:})    

    set(get(gui.vel_vers, 'XLabel'), 'String', 'Time (milliseconds)', fontSettings{:});
    set(get(gui.vel_vers, 'YLabel'), 'String', 'Velocity Version(deg/s)', fontSettings{:})    

    set(gui.popCnd, 'callback', {@popCnd_call, gui});  % Set the popup callback.
    set(gui.pbPlot, 'callback', {@pbPlot_call, gui});
    
    
    gui.conditionList = conditionsList;
    gui.conditionPos = conditionPos;
end

