function eyelinkData = loadEyelinkFile(filename, varargin)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VARNAME1,VARNAME2,VARNAME3,VARNAME4,VARNAME5,VARNAME6,VARNAME7,VARNAME8,VARNAME9,VARNAME10]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [VARNAME1,VARNAME2,VARNAME3,VARNAME4,VARNAME5,VARNAME6,VARNAME7,VARNAME8,VARNAME9,VARNAME10]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [VarName1,VarName2,VarName3,VarName4,VarName5,VarName6,VarName7,VarName8,VarName9,VarName10]
%   = importfile('AM_all_11_04_14_132841.asc',19, 45854);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/11/06 14:24:28

    %% Initialize variables with default values
    
    % column indices to use (default: time, LX, LY, RX, RY, meta)
    idx = [1, 2, 3, 5, 6];    
    
    delimiter = '\t';  
    startRow = 19;
    endRow = inf;

    if nargin > 1
        idx = varargin{1};
    end
   
    if nargin > 2
        startRow = varargin{2};
    end
    
     if nargin > 3
        endRow = varargin{3};
     end
    
    if nargin > 4
        delimiter = varargin{4};
    end
    
    nVals = max(idx);
    
    %% Format string for each line of text:
    formatSpec = [ repmat('%s', [1 nVals]) '%[^\n\r]'];
     

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
    dataArray = textscan(fileID, formatSpec, endRow(1) - startRow(1) + 1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);
    
    for block = 2:length(startRow)
        frewind(fileID);
        textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    %% Close the text file.
    fclose(fileID);

    eyelinkData = cat(2, dataArray{:, idx(:)});
end
